version: "3"
services:

  exodus:
    build: ./
    container_name: exodus
    image: exodus
    volumes:
      - ./exodus:/exodus/exodus:rw,cached
    depends_on:
      - minio
      - db
      - amqp
    ports:
      - "80:8000"
    networks:
      - backend

  minio:
    container_name: "minio"
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    volumes:
      - minio:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: exodusexodus
      MINIO_SECRET_KEY: exodusexodus
    networks:
      - backend
    command: ["minio", "server", "/data"]

  db:
    container_name: "db"
    image: postgres:11
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: exodus
      POSTGRES_PASSWORD: exodus
      POSTGRES_DB: exodus
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - backend

  amqp:
    container_name: "amqp"
    image: rabbitmq:3.7-alpine
    ports:
      - "5672:5672"
    networks:
      - backend

networks:
  backend:

volumes:
  minio:
  db:
