# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-23 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful_api', '0002_searchquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportInfos',
        ),
    ]
