# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('apk', models.FileField(upload_to='apks/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
