# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
