# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to='apks/ef8980d2-aed4-436f-94db-3814811eb33f'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/ef8980d2-aed4-436f-94db-3814811eb33f'),
        ),
    ]
