# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0002_auto_20170922_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to='apks/e0a894f2-071e-43a1-8334-2b84aeb498fd'),
        ),
    ]
