# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0004_auto_20170924_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to='apks/9a8dcd9d-a1db-4566-a7d9-f58dc11d4763'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/9a8dcd9d-a1db-4566-a7d9-f58dc11d4763'),
        ),
    ]
