# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0004_auto_20170923_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to='apks/664b66f0-cc05-4eb7-9d11-424b3e5f7c56'),
        ),
    ]
