# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0005_auto_20170924_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to='apks/7046eb4e-7279-4fed-9279-795b6c56af34'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/7046eb4e-7279-4fed-9279-795b6c56af34'),
        ),
    ]
