# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0005_auto_20170923_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to='apks/ef3adc55-978e-4034-9c07-d63227a315d2'),
        ),
    ]
