# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0006_auto_20170924_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to='apks/54100ea2-970c-444b-9f73-1af012dccba3'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/54100ea2-970c-444b-9f73-1af012dccba3'),
        ),
    ]
