# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0006_auto_20170923_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/481f4efb-bc79-4f6e-a949-9a44a73b6ad2'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to=models.TextField(default='apks/481f4efb-bc79-4f6e-a949-9a44a73b6ad2')),
        ),
    ]
