# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0007_auto_20170924_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to='apks/d52ac89b-0139-4328-a0e3-519f839f459d'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/d52ac89b-0139-4328-a0e3-519f839f459d'),
        ),
    ]
