# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0008_auto_20170924_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to='apks/b12c2e19-c0f6-4d3e-8c1f-4408f90456d1'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/b12c2e19-c0f6-4d3e-8c1f-4408f90456d1'),
        ),
    ]
