# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0009_auto_20170924_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to='apks/7b081c9b-c722-4efe-ba43-2a5bc82ca383'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/7b081c9b-c722-4efe-ba43-2a5bc82ca383'),
        ),
    ]
