# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0010_auto_20170924_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to='apks/9c0d6906-5aae-4e93-a0f8-887f4b2f23a0'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/9c0d6906-5aae-4e93-a0f8-887f4b2f23a0'),
        ),
    ]
