# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0011_auto_20170924_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to='apks/3aace74d-bd7d-4372-bd92-e5a5667e8f50'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/3aace74d-bd7d-4372-bd92-e5a5667e8f50'),
        ),
    ]
