# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0012_auto_20170924_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to='apks/09cc62db-d477-4ad3-b957-69e09d1bfe7c'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/09cc62db-d477-4ad3-b957-69e09d1bfe7c'),
        ),
    ]
