# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0014_auto_20170924_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to='apks/2f478b70-4ce5-447f-b04b-505122e7a6a6'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/2f478b70-4ce5-447f-b04b-505122e7a6a6'),
        ),
    ]
