# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0017_auto_20170924_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to='apks/e7d5834b-58b4-4ea3-a2e3-0a9b59938614'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/e7d5834b-58b4-4ea3-a2e3-0a9b59938614'),
        ),
    ]
