# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0023_auto_20170924_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to='apks/02199fdd-467f-4043-8c50-16bac0400827'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/02199fdd-467f-4043-8c50-16bac0400827'),
        ),
    ]
