# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0024_auto_20170924_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='handle',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/06af2dd0-96cb-4762-befb-e2803dd8e3de'),
        ),
    ]
