# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 13:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0025_auto_20170925_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='handle',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(message='Application handle doesnt comply', regex='^([\\w]+\\.)+[\\w]$')]),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/ed4043ef-473c-4126-92f4-646526e177a3'),
        ),
    ]
