# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 14:03
from __future__ import unicode_literals

import analysis_query.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0026_auto_20170925_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='handle',
            field=models.CharField(max_length=500, validators=[analysis_query.models.validate_handle]),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/81b83bb5-236b-4f4f-81b1-fbb8fa7b9bce'),
        ),
    ]
