# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0027_auto_20170925_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='handle',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='storage_path',
            field=models.TextField(default='apks/a6b995d7-c10b-4341-8116-127b059681f6'),
        ),
    ]
