# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-14 08:42
from __future__ import unicode_literals

import analysis_query.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0031_auto_20191201_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='apk',
            field=models.FileField(upload_to='', validators=[analysis_query.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='handle',
            field=models.CharField(blank=True, default='', max_length=500, validators=[analysis_query.models.validate_handle]),
        ),
    ]
