# Generated by Django 2.2.12 on 2020-06-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_query', '0032_auto_20191214_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='source',
            field=models.CharField(default='', max_length=50),
        ),
    ]
