# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionrule',
            name='description',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='description',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
