# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='code_signature',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='network_signature',
            field=models.CharField(default='', max_length=500),
        ),
    ]
