# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0002_auto_20170922_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrule',
            name='description',
            field=models.CharField(max_length=20000),
        ),
    ]
