# Generated by Django 2.2.12 on 2020-04-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0003_auto_20200208_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='code_signature',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='network_signature',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
