# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0003_auto_20170922_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
