# Generated by Django 2.2.27 on 2022-03-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0005_auto_20200704_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='documentation',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
