# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsquery',
            name='is_tracker',
            field=models.BooleanField(default=False),
        ),
    ]
