# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='apk_file',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='flow_file',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='pcap_file',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='dnsquery',
            name='network_analysis',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reports.NetworkAnalysis'),
        ),
        migrations.AlterField(
            model_name='httpanalysis',
            name='network_analysis',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reports.NetworkAnalysis'),
        ),
        migrations.AlterField(
            model_name='httppayload',
            name='http_analysis',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reports.HTTPAnalysis'),
        ),
        migrations.AlterField(
            model_name='httpsanalysis',
            name='network_analysis',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reports.NetworkAnalysis'),
        ),
        migrations.AlterField(
            model_name='httpspayload',
            name='https_analysis',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reports.HTTPSAnalysis'),
        ),
        migrations.AlterField(
            model_name='networkanalysis',
            name='report',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Report'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='application',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Application'),
        ),
        migrations.AlterField(
            model_name='report',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='udpanalysis',
            name='network_analysis',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reports.NetworkAnalysis'),
        ),
        migrations.AlterField(
            model_name='udppayload',
            name='udp_analysis',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reports.UDPAnalysis'),
        ),
    ]
