# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20170923_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='storage_path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
