# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20170926_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='icon_path',
            field=models.CharField(default='', max_length=500),
        ),
    ]
