# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_application_icon_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httppayload',
            name='destination_uri',
            field=models.CharField(max_length=2000),
        ),
    ]
