# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20170927_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_expired', models.BooleanField(default=False)),
                ('serial_number', models.CharField(default='', max_length=128)),
                ('issuer', models.CharField(default='', max_length=256)),
                ('subject', models.CharField(default='', max_length=256)),
                ('fingerprint', models.CharField(default='', max_length=256)),
                ('apk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Apk')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='app_uid',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='application',
            name='creator',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='downloads',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='icon_phash',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='version_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='bucket',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='class_list_file',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
