# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-14 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20180420_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnsquery',
            name='network_analysis',
        ),
        migrations.RemoveField(
            model_name='httpanalysis',
            name='network_analysis',
        ),
        migrations.RemoveField(
            model_name='httppayload',
            name='http_analysis',
        ),
        migrations.RemoveField(
            model_name='httpsanalysis',
            name='network_analysis',
        ),
        migrations.RemoveField(
            model_name='httpspayload',
            name='https_analysis',
        ),
        migrations.RemoveField(
            model_name='networkanalysis',
            name='report',
        ),
        migrations.RemoveField(
            model_name='udpanalysis',
            name='network_analysis',
        ),
        migrations.RemoveField(
            model_name='udppayload',
            name='udp_analysis',
        ),
        migrations.DeleteModel(
            name='DNSQuery',
        ),
        migrations.DeleteModel(
            name='HTTPAnalysis',
        ),
        migrations.DeleteModel(
            name='HTTPPayload',
        ),
        migrations.DeleteModel(
            name='HTTPSAnalysis',
        ),
        migrations.DeleteModel(
            name='HTTPSPayload',
        ),
        migrations.DeleteModel(
            name='NetworkAnalysis',
        ),
        migrations.DeleteModel(
            name='UDPAnalysis',
        ),
        migrations.DeleteModel(
            name='UDPPayload',
        ),
    ]
