# Generated by Django 2.2.13 on 2020-06-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_application_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
