# Generated by Django 3.2.15 on 2022-10-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20200630_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='subject',
            field=models.CharField(default='', max_length=500),
        ),
    ]
