# Generated by Django 3.2.15 on 2022-10-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20221004_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='version_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
