# Generated by Django 5.2.13 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_alter_application_version_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='version',
            field=models.CharField(max_length=100),
        ),
    ]
