# Generated by Django 5.2.13 on 2026-09-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_alter_application_version_code'),
        ('trackers', '0006_tracker_documentation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['handle', 'source', 'version', 'version_code'], name='app_handle_dedup_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['-creation_date'], name='report_creation_date_idx'),
        ),
    ]
