# Generated by Django 5.2.13 on 2026-09-12 15:37

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_application_app_handle_dedup_idx_and_more'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='application',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='app_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
